// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SportsVenueApi.Data;

#nullable disable

namespace SportsVenueApi.Migrations
{
    // Restored by hand: without these two attributes EF cannot see the migration at all. It
    // carries no target model because its operations are raw, idempotent SQL that needs none;
    // the model snapshot already describes both tables.
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420000000_AddWaitlistTables")]
    partial class AddWaitlistTables
    {
    }
}
